API製造
YasuhiroTanaka/invoice pull request #2
Opened 2018-02-10 02:19 UTC by YasuhiroTanaka

2018-02-17 06:35 UTC, kudarar requested changes

2018-02-17 06:35 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/DebugLog.java
> +public class DebugLog {
★Springではこのように至る所に冗長的に存在する非機能的な実装は
AOPという仕組みでコードをすっきりさせることができます。
あまりこのように記述は今はしないようになっています！

https://dev.classmethod.jp/etc/spring-aop-output-log/
DIフレームワークの恩恵を最大限活かして、業務の本質には関係がない部分の
実装を最小限にすることで、コーディングスピードや品質向上を図ることができますので、
参考にしてください！

2018-02-17 06:35 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/RequestPath.java
> +public class RequestPath {
修正しなくてもいいけど、パッケージ構成はdemo.constとかにして、
RequestPath という具体的なクラス名よりも、APIConstとか定数値を集約する命名のほうが、
拡張性が高い管理が出来ますね。まぁわかってやってるのかもですが。

また、たまたまなのか、String API = "/api"; のAPIという定数名も、APIという変数は抽象的すぎて
なんの定数が他の人がパット見てわからないですね。
私なら、API_BASE_PATH とかにするかな。

たまに？よく？
ERROR_CODE_4000="4000"; 
とか書いてるひとがいるけど、定数化する意味なくねー？（笑）って思っちゃいます。笑

2018-02-17 06:35 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/controller/InvoiceController.java
> +@Controller
「AutoDocJでコメントを自動生成すること。」
って見てくれたかな？
★既にコメント書いてくれてるから、悩ましいけど、プラグインはEclipseに入れて動作を見てみてほしいです！
こういう自動化ツールがあることを知るのもカリキュラムの目的として含めておりますゆえ。

2018-02-17 06:35 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/controller/InvoiceController.java
> +    private static final String CLASS = InvoiceController.class.getSimpleName();
AOPをうまく活用すると消えますね。

2018-02-17 06:35 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/controller/InvoiceController.java
> +    public int postInvoice(@RequestBody String body) {
★ObjectMapper でパースする部分ですが、@RestController を採用して、
`@RequestBody final InvoiceRequestForm invoiceRequestForm `
のように、モデルクラスへのマッピングをSpringに任せる事ができるとおもいます。

2018-02-17 06:35 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/form/InvoiceRequestForm.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
★★★
「Lomokを使って定形コードを自動生成すること。」

今回カリキュラム要件となっています。
setter, getter など、いろんなコードをスッキリさせることができるので、
是非使ってみてください。

2018-02-17 06:35 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/exception/ApiException.java
> +        return mErrorList.isEmpty();
★これ、いる？・・・
意図があればおしえてください。

2018-02-17 06:35 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/exception/ApiException.java
> +        private int mValue;
★mValue 細かいけど、この変数名はmCodeがいいとお思います。
（っていうか mってなんぞ？

2018-02-17 06:35 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/controller/InvoiceController.java
> +    private InvoiceService mInvoiceService;
★変数名の接頭辞の"m"ってなんですか？

2018-02-17 06:35 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/exception/ApiException.java
> +        private Map<String, Object> createErrorResponce() {
★createErrorResponce が2つあるのと、Map管理することで難読化されているように見えます。

Map化する目的はJsonパラメタ名の管理ですか？
ApiError を別パッケージで分離管理して、@JsonProperty で管理するほうがいいと思います。

2018-02-17 06:35 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/exception/ApiException.java
> +        super("api error");
★super("api error");
これ、いりますか？スタックトレースにだしたいから設定していますか？
それなら、やるとしても super(message); でもよいのでは？

2018-02-17 06:35 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/exception/ApiException.java
> +    public ApiException() {
このコンストラクタは必要ですか？

2018-02-17 06:35 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/controller/InvoiceController.java
> +    @ExceptionHandler({ Exception.class })
★Exception.class の部分ですが、ハンドルしていないRuntime系のエラーが出た場合は考慮しなくて良いでしょうか。
そのままアプリケーションが落ちてしまうように見えます。

2018-02-17 06:35 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/service/InvoiceService.java
> +    private void checkParameter(final InvoiceRequestForm form) {
修正必須にはしませんが、
この設計方針ですと、リクエストモデルができるたびに個別のチェックパラメータメソッドができます。
チェック条件はそれぞれ冗長して記述することになるかと思います。

org.springframework.validation.annotation.Validated;
で@Validをコントローラに付与することでエラーロジックを分離することができます。

2018-02-18 07:35 UTC, YasuhiroTanaka commented on invoice-api/src/main/java/com/example/demo/RequestPath.java
> +public class RequestPath {
RequestPathを削除しました

2018-02-18 07:54 UTC, YasuhiroTanaka commented on invoice-api/src/main/java/com/example/demo/controller/InvoiceController.java
> +    public int postInvoice(@RequestBody String body) {
@RestControllerにし、引数でInvoiceRequestForm を指定するように修正しました

2018-02-18 07:57 UTC, YasuhiroTanaka commented on invoice-api/src/main/java/com/example/demo/controller/InvoiceController.java
> +    @ExceptionHandler({ Exception.class })
RuntimeExceptionを500エラー、Exceptionを400エラーに変更しました

2018-02-18 08:28 UTC, YasuhiroTanaka commented on invoice-api/src/main/java/com/example/demo/exception/ApiException.java
> +        return mErrorList.isEmpty();
削除しました

2018-02-18 08:29 UTC, YasuhiroTanaka commented on invoice-api/src/main/java/com/example/demo/exception/ApiException.java
> +        private int mValue;
ApiErrorを外に出したことによってenumで定義することができなくなったため、削除しました

2018-02-18 08:30 UTC, YasuhiroTanaka commented on invoice-api/src/main/java/com/example/demo/controller/InvoiceController.java
> +    private InvoiceService mInvoiceService;
Androidの標準的なコーディング方法で、javaでは一般的なものと思っていましたが全く一般的なものではなかったため、全体的に修正しました

2018-02-18 08:31 UTC, YasuhiroTanaka commented on invoice-api/src/main/java/com/example/demo/exception/ApiException.java
> +        private Map<String, Object> createErrorResponce() {
ApiErrorを分離し、handleErrorでList<ApiError>を返すようにしました

2018-02-18 08:33 UTC, YasuhiroTanaka commented on invoice-api/src/main/java/com/example/demo/exception/ApiException.java
> +        super("api error");
スタックトレース出していないため、superコンストラクタを削除しました

2018-02-18 08:33 UTC, YasuhiroTanaka commented on invoice-api/src/main/java/com/example/demo/exception/ApiException.java
> +    public ApiException() {
削除しました

2018-02-18 14:59 UTC, YasuhiroTanaka commented on invoice-api/src/main/java/com/example/demo/DebugLog.java
> +public class DebugLog {
AOPを導入してInvoiceLoggerProxyでログを出力するように修正しました

2018-02-18 15:00 UTC, YasuhiroTanaka commented on invoice-api/src/main/java/com/example/demo/controller/InvoiceController.java
> +    private static final String CLASS = InvoiceController.class.getSimpleName();
削除しました

2018-02-18 15:00 UTC, YasuhiroTanaka commented on invoice-api/src/main/java/com/example/demo/form/InvoiceRequestForm.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
Lombokを導入し、getterをすべて削除しました

2018-02-18 23:43 UTC, YasuhiroTanaka commented on invoice-api/src/main/java/com/example/demo/controller/InvoiceController.java
> +@Controller
申し訳ございません。
JAutoDocを導入し、InvoiceLoggerProxyのコメントを自動生成しました

2018-02-24 01:34 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/RequestPath.java
> +public class RequestPath {
了解です！

2018-02-24 01:34 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/DebugLog.java
> +public class DebugLog {
素晴らしい

2018-02-24 02:01 UTC, kudarar requested changes

2018-02-24 02:01 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/controller/InvoiceController.java
> +@Controller
いえいえ。
JAutoDoc実行するだけで、コメント生成が楽になるので今後の参考にしてください。

2018-02-24 02:01 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/controller/InvoiceController.java
> +    private static final String CLASS = InvoiceController.class.getSimpleName();
GOODです！

2018-02-24 02:01 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/controller/InvoiceController.java
> +    private InvoiceService mInvoiceService;
Androidの標準的なコーディング方法
→え、そうなんだ！知らなかった。。現場だとスタンダードなんだねー。

2018-02-24 02:01 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/controller/InvoiceController.java
> +    public int postInvoice(@RequestBody String body) {
あれ？これ直ってますか？

2018-02-24 02:01 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/controller/InvoiceController.java
> +    public int postInvoice(@RequestBody String body) {
OKです！

2018-02-24 02:01 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/controller/InvoiceController.java
> +    @ExceptionHandler({ Exception.class })
WebのHTTPステータスコードになぞらえたエラーコードとなっていますが、
・400系はユーザに原因のあるエラー
・500件はサーバに原因のあるエラー
となります。
これとRuntimeException、Exceptionにマッピングすると、検査例外で500系を処理したいというケースが
きっと出てくるとおもうのでが、対応ができなくなってしまいます。

そこで、よくやるのがなるべく想定できるエラーは自分でcatchし、
最期にどうしても想定できないExceptionをThrowableでキャッチします。

ここは 下記に修正するだけで十分だったかと思います。
```
@ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
@ExceptionHandler({ Throwable.class })
```

2018-02-24 02:01 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/exception/ApiException.java
> +        private int mValue;
了解です。

2018-02-24 02:01 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/exception/ApiException.java
> +        super("api error");
了解です。

2018-02-24 02:01 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/exception/ApiException.java
> +    public ApiException() {
OKです。

2018-02-24 02:01 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/exception/ApiException.java
> +        return mErrorList.isEmpty();
OKです。

2018-02-24 02:01 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/exception/ApiException.java
> +        private Map<String, Object> createErrorResponce() {
了解です！

2018-02-24 02:01 UTC, kudarar commented on invoice-api/src/main/java/com/example/demo/form/InvoiceRequestForm.java
> +@JsonIgnoreProperties(ignoreUnknown = true)
すばらしい

2018-02-24 02:50 UTC, YasuhiroTanaka commented on invoice-api/src/main/java/com/example/demo/controller/InvoiceController.java
> +    @ExceptionHandler({ Exception.class })
500エラーをThrowable、400エラーをrequest不正で発生しうるエラーに指定しなおしました。

2018-02-24 08:53 UTC, merged